version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/nagatax/golang-library
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      # Check coding style
      - run: make gotools
      - run: make lint
      - run: make test
workflows:
  version: 2
  workflow:
    jobs:
      - build
